CREATE DATABASE M_Livros;

USE M_Livros;

CREATE TABLE Gêneros(
	IdGenero INT PRIMARY KEY IDENTITY
	,Descricao VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Ativo(
	IdAtivo INT PRIMARY KEY IDENTITY
	,Descricao INT
);

CREATE TABLE Autores(
	IdAutor INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(100) NOT NULL UNIQUE
	,Email VARCHAR(50) NOT NULL
	,IdAtivo INT FOREIGN KEY REFERENCES Ativo (IdAtivo)
	,DataNascimento DATE
);


CREATE TABLE Livros(
	IdLivro INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(100) NOT NULL
	,IdAutor INT FOREIGN KEY REFERENCES Autores (IdAutor)
	,IdGenero INT FOREIGN KEY REFERENCES Gêneros (IdGenero)
);