CREATE DATABASE M_SStop;
USE M_SStop;
CREATE TABLE Estilos(
	IdEstilo INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (200) UNIQUE NOT NULL
);

CREATE TABLE Artistas(
	IdArtista INT PRIMARY KEY IDENTITY
	,Nome VARCHAR (200) UNIQUE NOT NULL
	,IdEstilo INT FOREIGN KEY REFERENCES Estilos (IdEstilo)
);